---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
This page describes visualization of temperature changes in felt samples held under an incandescent lamp.

First, we load in the temperature data for each felt square. W = white, G = Grey, B = Black. Temperatures are in Celsius. 
```{r}
feltW<-c(22.4,23.7,23.8,23.9,24.1,23.9,24.3,24.1,24.2,23.9,24.2)
feltG<-c(22.5,23.8,24.2,24.6,24.8,25.2,25.7,26.1,25.9,26.2,26.8)
feltB<-c(22.3,24.1,24.7,25.4,25.9,26.5,27.3,28.5,28.9,29.3,30.4)
```

Next, we create a data vector for the time. Units are minutes. 
```{r}
timeMin<-c(0,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0)
```

Finally, we create a simple plot.
```{r}
plot(timeMin,feltW, pch=21,col="darkgrey",bg="white", type="o", lty=2, ylim=c(20,32), ylab="Temperature (°C)", xlab="Time (minutes)", main="Comparison of Felt Temperatures over Time")
points(timeMin, feltG, pch=21,col="darkgrey",bg="grey", type="o", lty=2)
points(timeMin, feltB, pch=21,col="darkgrey",bg="black", type="o", lty=2)
abline(h=seq(20,32,by=2),lty=3,col="lightgrey")
legend("topleft", legend=c("Felt Color: Black", "Felt Color: Grey", "Felt Color: White"), fill=c("black", "grey", "white"), cex=0.8)
```

